name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore https://github.com/suleman26/gitdata/blob/main/WebApplication1/WebApplication1/WebApplication1.csproj
    - name: Build https://github.com/suleman26/gitdata/blob/main/WebApplication1/WebApplication1/WebApplication1.csproj
      run: dotnet build https://github.com/suleman26/gitdata/blob/main/WebApplication1/WebApplication1/WebApplication1.csproj --no-restore
    - name: Test
      run: dotnet test https://github.com/suleman26/gitdata/blob/main/WebApplication1/WebApplication1/WebApplication1.csproj --no-build --verbosity normal
